site_name: 'Windmill Dark MkDocs Theme'
site_description: 'MkDocs theme focused on navigation and usability.'
site_author: 'Alexandre ZANNI'

repo_url: https://github.com/noraj1337/mkdocs-windmill-dark

theme_dir: mkdocs_windmill_dark

pages:
- Windmill Theme Dark:
  - Usage: index.md
  - Customization: customization.md
- Samples:
  - Sample Page A: sample-a.md
  - Sample Subfolder:
    - Sample Subpage A1: sample-a1.md
    - Sample Subpage A2: sample-a2.md
  - Sample Page B: sample-b.md

markdown_extensions:
  - toc:
      permalink: '#'

extra:
  history_buttons: false
  version: 0.1.2
